name: azure-cli
version: '2.0.7'
summary: Command-line tools for Azure.
description: |
  A great cloud needs great tools; we're excited to introduce Azure CLI 2.0,
  our next generation multi-platform command line experience for Azure.

grade: stable
confinement: classic

apps:
  azure-cli:
    command: az-wrapper

parts:
  pkg-deps:
    plugin: nil
    build-packages: ["libssl-dev", "libffi-dev", "build-essential", "python3.5"]
    stage-packages: ["libssl1.0.0", "libffi6"]

  wrapper:
    plugin: dump
    source: snap
    snap:
        - az-wrapper

  azure-cli:
    plugin: python
    after: ["pkg-deps"]
    python-packages: ["azure-cli"]
    process-dependency-links: true
    python-version: python3
    stage:
        - -lib/python3.5/site-packages/*/.*.swp

